############################## Site settings ##############################

title: UofT Smash
senpai: Henry Lu
project: https://github.com/nanosmasher/smash.skule.ca

colour:
  light: E74C3C
  overlight: EFEFEF
  dark: C0392B
  overdark: FEFEFE
  pmlight: 311b92
  pmdark: 673ab7

markdown: kramdown
permalink: '/tournament/:title/'
relative_permalinks: false
include: [.htaccess]
exclude: [LICENSE,README.md]
future: true

############################## Stuff you can touch  ##############################

keywords: ['UofT', 'Toronto', 'Skule', 'Engineering', 'Club', 'Super', 'Smash', 'Bros', 'Melee', 'Project M', 'Wii U']
description: 'Smash at UofT'
youtube: 'UCgyW1tIsYq1bfrdYZIMCnNA'
email: 'smash@smash.skule.ca'
facebook: '454304108002814'
